#!/usr/bin/env bash

OP="$HOME/.op"
echo $OP

rm -Rvf "$OP"
rm -vf $HOME/.emacs.d/projectile*

mkdir -p "$OP"
for D in "$@"
do
	touch $D/.projectile
	echo -n "$D" " " >> $OP/projectiles
    ctags.exe -a -f $OP/TAGS -Re $(realpath $D); 
	ls -lh $OP/TAGS
done

pushd $1
emacs
popd

for D in "$@"
do
	rm -vf $D/.projectile
done