#!/usr/bin/env bash

set -e
set -x

function system()
{
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        echo "linux";
    else
        if [[ "$OSTYPE" == "msys" ]]; then
            echo "msys";
        else
            echo "unknown";
        fi;
    fi
}

function winify() {
	if [[ "$(system)" = "msys"  ]]; then
		echo $1 | sed 's|^/\([a-z,A-Z]\)/|\1:/|';
	else
		echo $1;
	fi
}

function normalize() {
	echo $(winify $(realpath $1))
}
  
OP="$HOME/.op"
echo $OP

rm -Rvf "$OP"
rm -vf $HOME/.emacs.d/projectile*

mkdir -p "$OP"
for D in "$@"
do
	N=$(normalize $D)
	touch $N/.projectile
	echo -n "$N" " " >> $OP/projectiles
    ctags.exe -a -f $OP/TAGS -Re $N 
	ls -lh $OP/TAGS
done

pushd $1
emacs
popd

for D in "$@"
do
	rm -vf $D/.projectile
done