(setq copilot-node-executable "/opt/copilot/node.js/node-v20.11.0-linux-x64/bin/node")
(add-to-list 'load-path "~/.emacs.d/lisp/copilot/copilot.el")
;;(load "~/emacs.d/lisp/copilot/copilot.el/copilot.el")
(require 'copilot)
(message "ok")
