(defun jump-to-file-at-point ()
  (interactive)
  (save-excursion
	(let* ((line (thing-at-point 'line' 'no-properties))
		   (parts (split-string line))
		   (qfilename  (nth 1 parts))
		   (filename (replace-regexp-in-string "[\"<>]" "" qfilename))
		   (basename (file-name-nondirectory filename)))
	  (setq cmd (format "find $(cat ~/.op/projectiles) -type f -name \"%s\" | head -1" basename))
	  (require 'subr-x)
	  (setq result (string-trim (shell-command-to-string cmd)))
	  (message "found:%s" result)
	  ;; (sit-for 0.25) 
	  (find-file result)
	  )))

;;(switch-to-buffer "foo")
;;(jump-to-file-at-point)
